const BASE_URL = 'https://images.unsplash.com/photo-';
const COMMON_PARAMS =
  '?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&q=70';
const toSrc = (photoId: string) =>
  BASE_URL + photoId + COMMON_PARAMS + '&w=1080';
const toSrcSet = (photoId: string) =>
  [480, 640, 840]
    .map((w) => BASE_URL + photoId + COMMON_PARAMS + `&w=${w} ${w}w`)
    .join(', ');

const images = [
  {
    src: toSrc('1594653804388-0ad4242b28c2'),
    srcSet: toSrcSet('1594653804388-0ad4242b28c2'),
    placeholder:
      'data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQH/2wBDAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQH/wAARCAAIAAgDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAn/xAAeEAABBAMBAQEAAAAAAAAAAAAGAQIFBwAIEQQVIv/EABUBAQEAAAAAAAAAAAAAAAAAAAYH/8QAIBEBAAECBwEBAAAAAAAAAAAAAQIEEQADBSEiMUFRsf/aAAwDAQACEQMRAD8AlJT0lrBtdqyBg/pqGBFbtrCmowIGbLD/AGp9N8vAzykKhVswTetJBl41+kLEVTcH6nFcnMYxjes1Gqc+XMLEei3g/fv5ib0+nUplnBbyldZMlvKPa3Xt3VX1XfH/2Q==',
    width: 1080,
    height: 1080,
    color: '#040a14',
  },
  {
    src: BASE_URL + '1593889392960-817de7c25771' + COMMON_PARAMS,
    placeholder:
      'data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQH/2wBDAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQH/wAARCAAMAAgDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAr/xAAmEAABAgQEBwEAAAAAAAAAAAAFBgcAAQIDBAgWIQkkJjFCRlaR/8QAFQEBAQAAAAAAAAAAAAAAAAAAAAT/xAAaEQACAgMAAAAAAAAAAAAAAAAAAQIVUpHR/9oADAMBAAIRAxEAPwCppmc7zXvxaJEEOl3a0TheSCrxYNiaQyXWG3oeo+qlGmp/WaM7zhEhTacQvMopXYUAE+ox5UamG9EzEWsZQcuTsbeVUj9Mq/ymECCwnitLp//Z',
    width: 1080,
    height: 1618,
    color: '#d9dada',
  },
  {
    src: BASE_URL + '1594418569593-bdfdcf47a2cf' + COMMON_PARAMS,
    placeholder:
      'data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQH/2wBDAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQH/wAARCAANAAgDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAcJ/8QAJBAAAQMDBAEFAAAAAAAAAAAABAEDBQACBgcIERUxEiE2UcH/xAAVAQEBAAAAAAAAAAAAAAAAAAAHCP/EACMRAAEDAwIHAAAAAAAAAAAAAAECAxEEBRIAMQYTFCFBscH/2gAMAwEAAhEDEQA/AMzsv1+j9PtjWJY/K9qNkhRqn9OZ8X6lJxYDvPvwnsn5So7l7gGSbNSgCQFV3SR4OMDkDC3JA2TNky8hk35dl12xtIUm1/hLWhEftVE59aeKVG3Btjpelu3OStTgvldKkuBKYxYgAFtZMCTJUN4jclJcoqptWOaYjt5+j1r/2Q==',
    width: 1080,
    height: 1737,
    color: '#4d3b1f',
  },
  {
    src: BASE_URL + '1593959072487-3c17618454aa' + COMMON_PARAMS,
    placeholder:
      'data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQH/2wBDAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQH/wAARCAAFAAgDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAf/xAAhEAABAwQCAwEAAAAAAAAAAAABAwQFAAIGBxUhCCIjJf/EABQBAQAAAAAAAAAAAAAAAAAAAAj/xAAgEQABAwIHAAAAAAAAAAAAAAABAAIDEqEiMTJRgbHB/9oADAMBAAIRAxEAPwCrYl5g7zYa8xhcL67DaZiZZ1xrPBlo9kzj+ElwYhJNLI7zc2/NR+hNt3Z9OgSpSjXFoHHQTokmlrON2TbgE393X//Z',
    width: 1080,
    height: 735,
    color: '#86645c',
  },
  {
    src: BASE_URL + '1531279550271-23c2a77a765c' + COMMON_PARAMS,
    placeholder:
      'data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQH/2wBDAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQH/wAARCAAKAAgDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAgK/8QAJRAAAAQFAgcAAAAAAAAAAAAAAQQFBgADBxETAhQIEiElM4KR/8QAFQEBAQAAAAAAAAAAAAAAAAAABQb/xAAiEQABAgQHAQAAAAAAAAAAAAABAgUABAYxFkFRU2JxweH/2gAMAwEAAhEDEQA/AMzlT+F500sNmhcZhrmVxLWtidKI60iqiYKSI3FcQhv1bdxsI/YRUlUiZQu3X3typaRnZY5sMiVKzd8b/l5NOnJ73hFmu469MG0g406lhkhhlRITcvU3xOxr9zj/2Q==',
    width: 1080,
    height: 1350,
    color: '#081e26',
  },
  {
    src: BASE_URL + '1594725224909-0e66d59ed0f1' + COMMON_PARAMS,
    placeholder:
      'data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQH/2wBDAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQH/wAARCAAMAAgDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAgJ/8QAJxAAAAMGBAcAAAAAAAAAAAAABAUGAAEDBwgUAhUhMREWIyZBdbH/xAAUAQEAAAAAAAAAAAAAAAAAAAAG/8QAJREAAAIHCQAAAAAAAAAAAAAAAWEAAgMGQWKhBRESISUmUXGS/9oADAMBAAIRAxEAPwCQkrXhK9SIhfrADRuqA2Q63gJT5mgi/wB6fcsduP0+sbDtN1IzvJ4EeEXzIVcAIacXDwDjoyshO7+pButdvGJzGfA3ejLX2sIDJKdOriKlkudhDbzL0HKhnQDT/9k=',
    width: 1080,
    height: 1620,
    color: '#4a4b53',
  },
  {
    src: BASE_URL + '1594559414091-2a75d7c73a68' + COMMON_PARAMS,
    placeholder:
      'data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQH/2wBDAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQH/wAARCAAMAAgDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAcK/8QAJRAAAQIFBAEFAAAAAAAAAAAAAQUGAgQHESEAAwgTCRUiJTFB/8QAFQEBAQAAAAAAAAAAAAAAAAAABwj/xAAlEQABAgQEBwAAAAAAAAAAAAABAhEDBjFBAAQFUQcIEhMhIiT/2gAMAwEAAhEDEQA/ALVWLxTchaotuWfVLmCFiGUcpkomjKFFhcqajiwQV0oh9oPwQwTnP2AbNaVeDFRF900nUFhV20wz3pzT3uyXkRswmMgjMPZHcC9wCTmx/BppzTxumjKAQUaNLnSgsPniu3ofJYPQ2FWa+JnXy4SbniMyrWZjBWzjvwhQps5F96Pvj//Z',
    width: 1080,
    height: 1645,
    color: '#4980a7',
  },
];

export default images;
