version: 2.1

jobs:
  test:
    docker:
      - image: circleci/node:11.9.0
        environment:
          SHARP_IGNORE_GLOBAL_LIBVIPS: 1
    working_directory: ~/repo
    parallelism: 4
    steps:
      - checkout
      - restore_cache:
          name: Restore node_modules cache
          keys:
            - v1-node-{{ arch }}-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - v1-node-{{ arch }}-{{ .Branch }}-
            - v1-node-{{ arch }}-
      - run:
          name: Nodejs Version
          command: node --version
      - run:
          name: Install packages
          command: yarn --frozen-lockfile
      - run:
          name: Build packages
          command: yarn build
      - run:
          name: Test packages
          command: yarn test
      - save_cache:
          name: Save node_modules cache
          key: v1-node-{{ arch }}-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
  release:
    docker:
      - image: circleci/node:11.9.0
    working_directory: ~/repo
    parallelism: 4
    steps:
      - checkout
      - restore_cache:
          name: Restore node_modules cache
          keys:
            - v1-node-{{ arch }}-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - v1-node-{{ arch }}-{{ .Branch }}-
            - v1-node-{{ arch }}-
      - run:
          name: Install packages
          command: yarn --frozen-lockfile
      - run:
          name: Build packages
          command: yarn build
      - run:
          name: Run semantic release
          command: yarn run semantic-release
      - save_cache:
          name: Save node_modules cache
          key: v1-node-{{ arch }}-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules

workflows:
  test_and_release:
    jobs:
      - test
      - release:
          requires:
            - test
