version: 2.1

jobs:
  test:
    docker:
      - image: circleci/node:11.9.0
        environment:
          SHARP_IGNORE_GLOBAL_LIBVIPS: 1
    working_directory: ~/repo
    parallelism: 4
    steps:
      - checkout
      - restore_cache:
          name: Restore node_modules cache
          keys:
            - v1-node-{{ arch }}-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - v1-node-{{ arch }}-{{ .Branch }}-
            - v1-node-{{ arch }}-
      - run:
          name: Nodejs Version
          command: node --version
      - run:
          name: Install packages
          command: yarn --frozen-lockfile
      - run:
          name: Build packages
          command: yarn build
      - run:
          name: Test packages
          command: yarn test
      - save_cache:
          name: Save node_modules cache
          key: v1-node-{{ arch }}-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: ~/repo
          paths: .
  release:
    docker:
      - image: circleci/node:11.9.0
    working_directory: ~/repo
    parallelism: 4
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
        name: Authenticate with registry
        command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
      - run:
          name: Release
          command: yarn run publish

workflows:
  version: 2
  test_and_release:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: /^master$/
